sh ios/new.sh
sh ios/replace.sh
sh android/new.sh
sh android/replace.sh
sh search/new.sh
sh search/replace.sh
sh yserv/new.sh
sh yserv/replace.sh
sh db/new.sh
sh db/replace.sh
sh front/new.sh
sh front/replace.sh
